"use client";

import Image from "next/image";
import { useState } from "react";
import { AdminQuestion } from "@/services/api";
import RichText from "./RichText";

type Props={packageTitle:string;packageCode:string;level:string;questions:AdminQuestion[];durationMinutes?:number};

export default function QuestionBankTools({packageTitle,packageCode,level,questions,durationMinutes=60}:Props){
  const [preview,setPreview]=useState(false); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<Record<string,string>>({});
  const question=questions[index];
  function choose(key:string){if(!question)return;if(question.question_type==="multiple_choice"){const selected=new Set((answers[question.id]??"").split(",").filter(Boolean));if(selected.has(key))selected.delete(key);else selected.add(key);setAnswers(current=>({...current,[question.id]:[...selected].sort().join(",")}));return}setAnswers(current=>({...current,[question.id]:key}))}
  function chooseCategory(optionKey:string,label:string){if(!question)return;const values=Object.fromEntries((answers[question.id]??"").split(";").filter(Boolean).map(part=>part.split("=",2)));values[optionKey]=label;setAnswers(current=>({...current,[question.id]:Object.entries(values).map(([key,value])=>`${key}=${value}`).join(";")}))}
  function printPDF(){const oldTitle=document.title;document.title=`${packageCode}-${packageTitle}`;window.print();window.setTimeout(()=>{document.title=oldTitle},500)}
  const answered=(item:AdminQuestion)=>Boolean(answers[item.id]);
  return <>
    <div className="question-bank-tools"><button className="button secondary" type="button" disabled={!questions.length} onClick={()=>{setIndex(0);setPreview(true)}}>Preview Tes</button><button className="button secondary" type="button" disabled={!questions.length} onClick={printPDF}>Cetak / Simpan PDF</button><span>{questions.length} soal siap ditampilkan</span></div>
    {preview&&question&&<div className="preview-backdrop" role="presentation" onMouseDown={()=>setPreview(false)}><section className="preview-shell" role="dialog" aria-modal="true" aria-label={`Preview tes ${packageTitle}`} onMouseDown={event=>event.stopPropagation()}>
      <header className="preview-header"><div><small>MODE PREVIEW · Tidak menyimpan hasil</small><strong>{packageTitle}</strong><span>{packageCode} · {level}</span></div><div className="timer-box"><small>Durasi tes</small><strong>{durationMinutes}:00</strong></div><button className="preview-close" type="button" aria-label="Tutup preview" onClick={()=>setPreview(false)}>×</button></header>
      <div className="preview-layout"><main className="card preview-question"><div className="question-meta"><span>{question.subject_name}</span><span>Soal {index+1} dari {questions.length}</span></div><div className="question-content"><RichText content={question.content_text}/><QuestionImage src={question.question_image_url} alt="Gambar soal"/></div>
      {question.question_type==="category"?<div className="category-answer-table">{question.options.map(option=><div className="category-answer-row" key={option.key}><div><b>{option.key}</b><span><RichText content={option.content}/><QuestionImage src={option.image_url} alt={`Gambar ${option.key}`}/></span></div><div>{question.category_labels.map(label=>{const chosen=(answers[question.id]??"").split(";").includes(`${option.key}=${label}`);return <button type="button" className={chosen?"selected":""} onClick={()=>chooseCategory(option.key,label)} key={label}>{label}</button>})}</div></div>)}</div>:<div className="answer-list">{question.options.map(option=>{const selected=question.question_type==="multiple_choice"?(answers[question.id]??"").split(",").includes(option.key):answers[question.id]===option.key;return <button type="button" className={`option ${selected?"selected":""}`} onClick={()=>choose(option.key)} key={option.key}><span className="option-key">{selected&&question.question_type==="multiple_choice"?"✓":option.key}</span><span><RichText content={option.content}/><QuestionImage src={option.image_url} alt={`Gambar pilihan ${option.key}`}/></span></button>})}</div>}
      <footer className="exam-actions"><button className="button secondary" type="button" disabled={index===0} onClick={()=>setIndex(current=>current-1)}>Sebelumnya</button>{index<questions.length-1?<button className="button" type="button" onClick={()=>setIndex(current=>current+1)}>Selanjutnya</button>:<button className="button submit-button" type="button" onClick={()=>setPreview(false)}>Selesai preview</button>}</footer></main>
      <aside className="card question-panel preview-panel"><div className="panel-summary"><strong>{questions.filter(answered).length}/{questions.length}</strong><span>soal dicoba</span></div><div className="numbers">{questions.map((item,itemIndex)=><button type="button" className={`number ${answered(item)?"done":""} ${itemIndex===index?"current":""}`} onClick={()=>setIndex(itemIndex)} key={item.id}>{itemIndex+1}</button>)}</div><div className="legend"><span><i className="done"/>Dicoba</span><span><i/>Belum</span></div><p className="preview-note">Jawaban dalam preview hanya simulasi dan tidak masuk ke hasil siswa.</p></aside></div>
    </section></div>}
    <section className="question-bank-print"><header><p>PAKET SOAL · {level}</p><h1>{packageTitle}</h1><div><span>Kode: <b>{packageCode}</b></span><span>Jumlah soal: <b>{questions.length}</b></span><span>Durasi: <b>{durationMinutes} menit</b></span></div></header><div className="print-student"><span>Nama: __________________________________</span><span>Kelas: ______________</span><span>Tanggal: ______________</span></div>{questions.map((item,itemIndex)=><article className="print-question" key={item.id}><div className="print-question-number">{itemIndex+1}</div><div><small>{item.subject_name}</small><p><RichText content={item.content_text}/></p><QuestionImage src={item.question_image_url} alt="Gambar soal"/><ol type="A">{item.options.map(option=><li key={option.key}><RichText content={option.content}/><QuestionImage src={option.image_url} alt={`Gambar ${option.key}`}/></li>)}</ol></div></article>)}<section className="print-answer-key"><h2>Kunci Jawaban dan Pembahasan</h2>{questions.map((item,index)=><div key={item.id}><b>{index+1}. {item.correct_answer}</b>{item.explanation_text&&<p><RichText content={item.explanation_text}/></p>}</div>)}</section><footer>Dicetak dari sistem bank soal · {packageCode}</footer></section>
  </>
}

function QuestionImage({src,alt}:{src?:string;alt:string}){return src?<Image className="question-media" src={src} alt={alt} width={800} height={500} unoptimized/>:null}
