"use client";

import { FormEvent, useState } from "react";
import { api, HeroSlide, SiteSettings } from "@/services/api";
import BrandLogo from "./BrandLogo";

export default function SiteSettingsPanel({initial,onSaved}:{initial:SiteSettings;onSaved:(settings:SiteSettings)=>void}){
  const [value,setValue]=useState<SiteSettings>(()=>structuredClone(initial));
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const field=<K extends keyof SiteSettings>(key:K,next:SiteSettings[K])=>setValue(current=>({...current,[key]:next}));
  const changeSlide=(index:number,patch:Partial<HeroSlide>)=>field("hero_slides",value.hero_slides.map((item,i)=>i===index?{...item,...patch}:item));
  const changeStat=(slideIndex:number,statIndex:number,part:0|1,next:string)=>changeSlide(slideIndex,{stats:value.hero_slides[slideIndex].stats.map((stat,i)=>i===statIndex?stat.map((text,j)=>j===part?next:text):stat)});
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");setError("");try{const saved=await api.updateSiteSettings(value);setValue(structuredClone(saved));onSaved(saved);setMessage("Pengaturan berhasil disimpan dan langsung diterapkan.")}catch(reason){setError(reason instanceof Error?reason.message:"Pengaturan gagal disimpan.")}finally{setSaving(false)}}
  function addSlide(){const id=`slide-${Date.now()}`;field("hero_slides",[...value.hero_slides,{id,eyebrow:"Informasi terbaru",title:"Judul slider baru",lead:"Tuliskan informasi yang ingin ditampilkan kepada pengunjung.",stats:[["Aktif","Informasi"],["Mudah","Digunakan"],["Aman","Terpercaya"],["24/7","Dapat diakses"]]}])}
  function uploadLogo(file?:File){if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setError("Logo harus berformat PNG, JPG, atau WebP.");return}if(file.size>1024*1024){setError("Ukuran logo maksimal 1 MB.");return}const reader=new FileReader();reader.onload=()=>{field("logo_data_url",String(reader.result));setError("")};reader.onerror=()=>setError("Logo gagal dibaca.");reader.readAsDataURL(file)}
  return <form className="settings-view" onSubmit={save}>
    <div className="settings-heading"><div><p className="eyebrow">Pusat konfigurasi</p><h2>Pengaturan sistem</h2><p className="muted">Kelola tampilan publik dan nilai bawaan operasional tanpa mengubah kode.</p></div><button className="button" disabled={saving}>{saving?"Menyimpan...":"Simpan semua perubahan"}</button></div>
    {message&&<p className="finance-success">{message}</p>}{error&&<p className="error">{error}</p>}
    <section className="card settings-card"><div className="settings-card-title"><div><h3>Identitas dan kontak</h3><p>Ditampilkan pada halaman depan dan seluruh panel.</p></div><span>Publik</span></div><div className="logo-upload"><BrandLogo logoDataURL={value.logo_data_url}/><div className="logo-upload-copy"><strong>Logo platform</strong><small>PNG, JPG, atau WebP. Maksimal 1 MB; disarankan berbentuk persegi.</small></div><div className="logo-upload-actions"><label className="button secondary">Pilih logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadLogo(e.target.files?.[0])}/></label>{value.logo_data_url&&<button type="button" className="danger-action" onClick={()=>field("logo_data_url","")}>Hapus logo</button>}</div></div><div className="settings-grid"><label>Nama platform<input value={value.platform_name} maxLength={80} required onChange={e=>field("platform_name",e.target.value)}/></label><label>Tagline platform<input value={value.platform_tagline} maxLength={180} onChange={e=>field("platform_tagline",e.target.value)}/></label><label>Email bantuan<input type="email" value={value.support_email} maxLength={160} onChange={e=>field("support_email",e.target.value)}/></label><label>Nomor WhatsApp<input value={value.whatsapp} maxLength={32} placeholder="6281234567890" onChange={e=>field("whatsapp",e.target.value)}/></label><label>URL Instagram<input type="url" value={value.instagram_url} maxLength={300} placeholder="https://instagram.com/..." onChange={e=>field("instagram_url",e.target.value)}/></label><label>URL YouTube<input type="url" value={value.youtube_url} maxLength={300} placeholder="https://youtube.com/@..." onChange={e=>field("youtube_url",e.target.value)}/></label></div></section>
    <section className="card settings-card"><div className="settings-card-title"><div><h3>Kecepatan slider</h3><p>Tentukan jeda perpindahan otomatis pada halaman depan.</p></div><span>Otomatis</span></div><div className="settings-grid"><label>Slider utama (detik)<input type="number" min="2" max="30" value={value.hero_interval_ms/1000} onChange={e=>field("hero_interval_ms",Number(e.target.value)*1000)}/></label><label>Slider paket (detik)<input type="number" min="2" max="30" value={value.catalog_interval_ms/1000} onChange={e=>field("catalog_interval_ms",Number(e.target.value)*1000)}/></label></div></section>
    <section className="card settings-card"><div className="settings-card-title"><div><h3>Nilai bawaan paket dan ujian</h3><p>Otomatis mengisi formulir paket baru milik admin dan guru.</p></div><span>Default</span></div><div className="settings-grid four"><label>Masa aktif paket (hari)<input type="number" min="1" max="3650" value={value.default_package_validity_days} onChange={e=>field("default_package_validity_days",Number(e.target.value))}/></label><label>Durasi ujian (menit)<input type="number" min="1" max="1440" value={value.default_exam_duration_minutes} onChange={e=>field("default_exam_duration_minutes",Number(e.target.value))}/></label><label>Jumlah soal<input type="number" min="1" max="1000" value={value.default_exam_total_questions} onChange={e=>field("default_exam_total_questions",Number(e.target.value))}/></label><label>Nilai lulus<input type="number" min="0" max="100" step="0.01" value={value.default_passing_score} onChange={e=>field("default_passing_score",Number(e.target.value))}/></label></div></section>
    <section className="settings-slides"><div className="settings-card-title"><div><h3>Konten slider halaman depan</h3><p>Urutan di bawah sama dengan urutan tayang.</p></div><button type="button" className="button secondary" disabled={value.hero_slides.length>=10} onClick={addSlide}>+ Tambah slide</button></div>{value.hero_slides.map((slide,index)=><article className="card slide-editor" key={slide.id}><div className="slide-editor-head"><strong>Slide {index+1}</strong><button type="button" className="danger-action" disabled={value.hero_slides.length===1} onClick={()=>field("hero_slides",value.hero_slides.filter((_,i)=>i!==index))}>Hapus</button></div><div className="settings-grid"><label>Label kecil<input value={slide.eyebrow} maxLength={100} onChange={e=>changeSlide(index,{eyebrow:e.target.value})}/></label><label>Judul<input value={slide.title} maxLength={180} required onChange={e=>changeSlide(index,{title:e.target.value})}/></label></div><label>Deskripsi<textarea value={slide.lead} maxLength={500} onChange={e=>changeSlide(index,{lead:e.target.value})}/></label><div className="slide-stats">{slide.stats.map((stat,statIndex)=><div key={statIndex}><input aria-label={`Nilai statistik ${statIndex+1}`} value={stat[0]} maxLength={30} onChange={e=>changeStat(index,statIndex,0,e.target.value)}/><input aria-label={`Label statistik ${statIndex+1}`} value={stat[1]} maxLength={60} onChange={e=>changeStat(index,statIndex,1,e.target.value)}/></div>)}</div></article>)}</section>
  </form>
}
