"use client";

import { FormEvent, useState } from "react";
import { api, SiteSettings } from "@/services/api";
import BrandLogo from "./BrandLogo";

export default function SiteSettingsPanel({initial,onSaved}:{initial:SiteSettings;onSaved:(settings:SiteSettings)=>void}){
  const [value,setValue]=useState<SiteSettings>(()=>structuredClone(initial));
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const field=<K extends keyof SiteSettings>(key:K,next:SiteSettings[K])=>setValue(current=>({...current,[key]:next}));
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");setError("");try{const saved=await api.updateSiteSettings(value);setValue(structuredClone(saved));onSaved(saved);setMessage("Pengaturan berhasil disimpan dan langsung diterapkan.")}catch(reason){setError(reason instanceof Error?reason.message:"Pengaturan gagal disimpan.")}finally{setSaving(false)}}
  function addSlide(){const id=`slide-${Date.now()}`;field("hero_slides",[...value.hero_slides,{id,image_data_url:"",title:"Tulisan slider baru"}]);}
  function uploadSlideImage(index:number,file?:File){if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setError("Gambar slider harus berformat PNG, JPG, atau WebP.");return}if(file.size>2.5*1024*1024){setError("Ukuran gambar slider maksimal 2,5 MB.");return}const reader=new FileReader();reader.onload=()=>{field("hero_slides",value.hero_slides.map((slide,i)=>i===index?{...slide,image_data_url:String(reader.result)}:slide));setError("")};reader.onerror=()=>setError("Gambar slider gagal dibaca.");reader.readAsDataURL(file)}
  function uploadLogo(file?:File){if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setError("Logo harus berformat PNG, JPG, atau WebP.");return}if(file.size>1024*1024){setError("Ukuran logo maksimal 1 MB.");return}const reader=new FileReader();reader.onload=()=>{field("logo_data_url",String(reader.result));setError("")};reader.onerror=()=>setError("Logo gagal dibaca.");reader.readAsDataURL(file)}
  function uploadFavicon(file?:File){if(!file)return;if(!["image/png","image/jpeg","image/webp","image/svg+xml"].includes(file.type)){setError("Favicon harus berformat PNG, JPG, WebP, atau SVG.");return}if(file.size>512*1024){setError("Ukuran favicon maksimal 512 KB.");return}const reader=new FileReader();reader.onload=()=>{field("favicon_data_url",String(reader.result));setError("")};reader.onerror=()=>setError("Favicon gagal dibaca.");reader.readAsDataURL(file)}
  return <form className="settings-view" onSubmit={save}>
    <div className="settings-heading"><div><p className="eyebrow">Pusat konfigurasi</p><h2>Pengaturan sistem</h2><p className="muted">Kelola tampilan publik dan nilai bawaan operasional tanpa mengubah kode.</p></div><button className="button" disabled={saving}>{saving?"Menyimpan...":"Simpan semua perubahan"}</button></div>
    {message&&<p className="finance-success">{message}</p>}{error&&<p className="error">{error}</p>}
    <section className="card settings-card"><div className="settings-card-title"><div><h3>Identitas dan kontak</h3><p>Ditampilkan pada halaman depan dan seluruh panel.</p></div><span>Publik</span></div><div className="logo-upload"><BrandLogo logoDataURL={value.logo_data_url}/><div className="logo-upload-copy"><strong>Logo platform</strong><small>PNG, JPG, atau WebP. Maksimal 1 MB; disarankan berbentuk persegi.</small></div><div className="logo-upload-actions"><label className="button secondary">Pilih logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadLogo(e.target.files?.[0])}/></label>{value.logo_data_url&&<button type="button" className="danger-action" onClick={()=>field("logo_data_url","")}>Hapus logo</button>}</div></div><div className="logo-upload favicon-upload"><div className="favicon-preview">{value.favicon_data_url?<span className="favicon-img" style={{backgroundImage:`url(${value.favicon_data_url})`}}/>:<span>?</span>}</div><div className="logo-upload-copy"><strong>Favicon (ikon tab browser)</strong><small>PNG, JPG, WebP, atau SVG. Maksimal 512 KB.</small></div><div className="logo-upload-actions"><label className="button secondary">Pilih favicon<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>uploadFavicon(e.target.files?.[0])}/></label>{value.favicon_data_url&&<button type="button" className="danger-action" onClick={()=>field("favicon_data_url","")}>Hapus favicon</button>}</div></div><div className="settings-grid"><label>Nama platform<input value={value.platform_name} maxLength={80} required onChange={e=>field("platform_name",e.target.value)}/></label><label>Tagline platform<input value={value.platform_tagline} maxLength={180} onChange={e=>field("platform_tagline",e.target.value)}/></label><label>Email bantuan<input type="email" value={value.support_email} maxLength={160} onChange={e=>field("support_email",e.target.value)}/></label><label>Nomor WhatsApp<input value={value.whatsapp} maxLength={32} placeholder="6281234567890" onChange={e=>field("whatsapp",e.target.value)}/></label><label>URL Instagram<input type="url" value={value.instagram_url} maxLength={300} placeholder="https://instagram.com/..." onChange={e=>field("instagram_url",e.target.value)}/></label><label>URL YouTube<input type="url" value={value.youtube_url} maxLength={300} placeholder="https://youtube.com/@..." onChange={e=>field("youtube_url",e.target.value)}/></label></div></section>
    <section className="card settings-card"><div className="settings-card-title"><div><h3>Kecepatan slider</h3><p>Tentukan jeda perpindahan otomatis pada halaman depan.</p></div><span>Otomatis</span></div><div className="settings-grid"><label>Slider utama (detik)<input type="number" min="2" max="30" value={value.hero_interval_ms/1000} onChange={e=>field("hero_interval_ms",Number(e.target.value)*1000)}/></label><label>Slider paket (detik)<input type="number" min="2" max="30" value={value.catalog_interval_ms/1000} onChange={e=>field("catalog_interval_ms",Number(e.target.value)*1000)}/></label></div></section>
    <section className="card settings-card"><div className="settings-card-title"><div><h3>Nilai bawaan paket dan ujian</h3><p>Otomatis mengisi formulir paket baru milik admin dan guru.</p></div><span>Default</span></div><div className="settings-grid four"><label>Masa aktif paket (hari)<input type="number" min="1" max="3650" value={value.default_package_validity_days} onChange={e=>field("default_package_validity_days",Number(e.target.value))}/></label><label>Durasi ujian (menit)<input type="number" min="1" max="1440" value={value.default_exam_duration_minutes} onChange={e=>field("default_exam_duration_minutes",Number(e.target.value))}/></label><label>Jumlah soal<input type="number" min="1" max="1000" value={value.default_exam_total_questions} onChange={e=>field("default_exam_total_questions",Number(e.target.value))}/></label><label>Nilai lulus<input type="number" min="0" max="100" step="0.01" value={value.default_passing_score} onChange={e=>field("default_passing_score",Number(e.target.value))}/></label></div></section>
    <section className="settings-slides"><div className="settings-card-title"><div><h3>Slider halaman depan</h3><p>Unggah gambar untuk setiap slide; tulisan tampil di bawah slider. Urutan di bawah sama dengan urutan tayang.</p></div><button type="button" className="button secondary" disabled={value.hero_slides.length>=10} onClick={addSlide}>+ Tambah slide</button></div>{value.hero_slides.map((slide,index)=><article className="card slide-editor" key={slide.id}><div className="slide-editor-head"><strong>Slide {index+1}</strong><button type="button" className="danger-action" disabled={value.hero_slides.length===1} onClick={()=>field("hero_slides",value.hero_slides.filter((_,i)=>i!==index))}>Hapus</button></div><div className="slide-image-row"><div className="slide-image-preview" style={slide.image_data_url?{backgroundImage:`url(${slide.image_data_url})`}:undefined}>{slide.image_data_url?"":<span>Belum ada gambar</span>}</div><div className="slide-image-actions"><label className="button secondary">Pilih gambar<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadSlideImage(index,e.target.files?.[0])}/></label>{slide.image_data_url&&<button type="button" className="danger-action" onClick={()=>field("hero_slides",value.hero_slides.map((item,i)=>i===index?{...item,image_data_url:""}:item))}>Hapus gambar</button>}<p className="muted">PNG, JPG, atau WebP. Maksimal 2,5 MB.</p></div></div><label>Tulisan di bawah slider<input value={slide.title} maxLength={500} placeholder="Tulisan yang tampil di bawah gambar slider" onChange={e=>field("hero_slides",value.hero_slides.map((item,i)=>i===index?{...item,title:e.target.value}:item))}/></label></article>)}</section>
  </form>
}
